# Generated by Django 6.0.3 on 2026-03-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_alter_department_name_alter_employee_hired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='departments.department'),
        ),
    ]
